Repository elan-ev/tobira, pull requests merged in 2022-12, with the labels that each got.

#616 Update docs, fix `fixtures.sql`, and add colors to `db reset` command
  backend/src/db/cmd.rs
  docs/docs/dev/data.md
  docs/docs/dev/index.md
  util/fixtures.sql
Labels: changelog:admin, changelog:dev

#615 Improve and fix some docs
  backend/src/auth/mod.rs
  backend/src/db/mod.rs
  docs/docs/setup/config.md
  docs/docs/setup/config.toml
Labels: changelog:nope

#618 Fix some typos in translation and docs
  docs/docs/dev/data.md
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
Labels: changelog:nope

#619 Fix doc deployment + some housekeeping
  docs/docs/dev/data.md
  docs/package-lock.json
Labels: kind:documentation, area:ci, kind:bug, area:infrastructure, dependencies, changelog:nope

#595 Split "manage single video" page into multiple pages
  backend/src/api/model/search/realm.rs
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/Burger.tsx
  frontend/src/layout/Navigation.tsx
  frontend/src/layout/Root.tsx
  frontend/src/router.tsx
  frontend/src/routes/Search.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/routes/manage/Video/Single.tsx
  frontend/src/routes/manage/Video/TechnicalDetails.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/index.tsx
  frontend/src/ui/metadata.tsx
Labels: changelog:user

#587 Automatic login for Studio and Editor
  .deployment/templates/config.toml
  backend/src/api/context.rs
  backend/src/api/jwt.rs
  backend/src/api/mod.rs
  backend/src/api/query.rs
  backend/src/auth/jwt.rs
  backend/src/auth/mod.rs
  backend/src/config/opencast.rs
  backend/src/http/assets.rs
  backend/src/http/handlers.rs
  docs/docs/setup/auth/index.md
  docs/docs/setup/config.toml
  docs/docs/setup/jwt.md
  docs/docs/setup/requirements.md
  frontend/src/config.ts
  frontend/src/relay/auth.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/schema.graphql
  util/dev-config/config.toml
  util/scripts/check-system.sh
Labels: area:api, area:backend, area:frontend, kind:new-feature, area:opencast, area:auth, changelog:user

#627 Fix CI badge in README
  README.md
Labels: changelog:nope

#626 Generalize installation docs
  docs/docs/setup/auth/index.md
  docs/docs/setup/debs.md
  docs/docs/setup/deploy.md
  docs/docs/setup/index.md
  docs/docs/setup/install.md
  docs/docs/setup/metrics.md
  docs/docs/setup/resync.md
Labels: changelog:admin
