Repository elan-ev/tobira, pull requests merged in 2022-09, with the labels that each got.

#539 Fix video playback bug by updating Paella and adjusting the data we feed it
  frontend/package-lock.json
  frontend/package.json
  frontend/src/typings/paella-core.d.ts
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user

#542 Update to MeiliSearch 0.28.1
  .deployment/deploy.yml
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/api/model/search/mod.rs
  backend/src/search/meta.rs
  backend/src/search/mod.rs
  backend/src/search/util.rs
  docs/run-requirements.md
  util/containers/docker-compose.yml
Labels: changelog:breaking

#543 Better event selector in block edit mode (plus other improvements)
  backend/src/api/model/event.rs
  backend/src/api/model/search/mod.rs
  backend/src/api/query.rs
  backend/src/config/color.rs
  backend/src/config/theme.rs
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Search.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/Content/Block.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
  frontend/src/routes/manage/Realm/Content/index.tsx
  frontend/src/schema.graphql
  frontend/src/ui/SearchableSelect.tsx
  frontend/src/ui/Video.tsx
  frontend/src/ui/Waiting.tsx
Labels: changelog:user

#546 Link `libssl` and `libz` statically
  backend/Cargo.lock
  backend/Cargo.toml
Labels: changelog:admin

#536 Clean up local store mods when navigating away from realm editor
  frontend/src/routes/manage/Realm/Content/Block.tsx
Labels: changelog:user

#551 Add, improve, rewrite and automatically render and deploy documentation
  .github/workflows/ci.yml
  .github/workflows/deploy-docs.yml
  README.md
  docs/.gitignore
  docs/CONTRIBUTING.md
  docs/README.md
  docs/auth/README.md
  docs/deploy.md
  docs/docs/dev/build/dev.md
  docs/docs/dev/build/index.md
  docs/docs/dev/build/release.md
  docs/docs/dev/build/requirements.md
  docs/docs/dev/contribute.md
  docs/docs/dev/data.md
  docs/docs/dev/editor.md
  docs/docs/dev/index.md
  docs/docs/dev/overview.md
  docs/docs/img/_architecture-inkscape.svg
  docs/docs/img/architecture.svg
  docs/docs/intro.md
  docs/docs/overview.md
  docs/docs/setup/ansible-example.md
  docs/docs/setup/auth/example-all-own.md
  docs/docs/setup/auth/example-all-tobira.md
  docs/docs/setup/auth/index.md
  docs/docs/setup/auth/login-page.md
  docs/docs/setup/auth/session-management.md
  docs/docs/setup/config.md
  docs/docs/setup/config.toml
  docs/docs/setup/deploy.md
  docs/docs/setup/index.md
  docs/docs/setup/jwt.md
  docs/docs/setup/requirements.md
  docs/docs/setup/update.md
  docs/docs/supported-browsers.md
  docs/docs/versioning-policy.md
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  docs/run-requirements.md
  util/scripts/on-backend-change.sh
Labels: changelog:admin, changelog:dev
