Repository elan-ev/tobira, pull requests merged in 2022-08, with the labels that each got.

#506 Fix video page for videos with an audio(-only) track, and fix the infinite loop in our error handling caused by it
  frontend/src/relay/boundary.tsx
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user

#512 Fix i18next warning on "new page" page
  frontend/src/routes/manage/Realm/AddChild.tsx
Labels: changelog:dev

#513 Fix two minor Safari style bugs/problems
  frontend/src/layout/header/UserBox.tsx
  frontend/src/routes/manage/Video/index.tsx
Labels: changelog:user

#514 Refactor waiting vs. ready series and pass title in `mountSeries`
  backend/src/api/common.rs
  backend/src/api/model/block/mod.rs
  backend/src/api/model/event.rs
  backend/src/api/model/series.rs
  backend/src/api/mutation.rs
  backend/src/api/query.rs
  frontend/src/routes/Series.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Series.tsx
  frontend/src/routes/manage/Realm/General.tsx
  frontend/src/routes/manage/Video/Single.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/util/index.ts
  util/fixtures.sql
Labels: changelog:dev

#515 Make `mountSeries` "rename" the target realm
  backend/src/api/model/block/mod.rs
  backend/src/api/model/realm/mutations.rs
  backend/src/api/mutation.rs
Labels: changelog:dev

#517 Print newlines (soft `clear`) in dev watch scripts to make terminal output easier to read
  util/scripts/clr.sh
  util/scripts/on-backend-change.sh
  util/scripts/watch-frontend.sh
Labels: changelog:dev

#516 Automatically rebuild search index when necessary (plus refactoring)
  backend/src/api/common.rs
  backend/src/api/err.rs
  backend/src/api/mod.rs
  backend/src/api/model/search/mod.rs
  backend/src/api/query.rs
  backend/src/api/util.rs
  backend/src/cmd/check.rs
  backend/src/db/cmd.rs
  backend/src/http/handlers.rs
  backend/src/main.rs
  backend/src/search/cmd.rs
  backend/src/search/meta.rs
  backend/src/search/mod.rs
  backend/src/search/update.rs
  backend/src/search/writer.rs
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/relay/boundary.tsx
  frontend/src/routes/Search.tsx
  frontend/src/schema.graphql
Labels: changelog:breaking, changelog:admin

#520 Normalize `margin` for some elements
  frontend/src/GlobalStyle.tsx
Labels: area:frontend, kind:bug, area:design, changelog:user

#519 Improve icon for going to "my videos" from "manage single video" page
  frontend/src/routes/manage/Video/Single.tsx
Labels: changelog:user

#522 Add `roles` field to `User`-s
  backend/src/api/model/user.rs
  frontend/src/schema.graphql
Labels: changelog:dev

#526 Improve "sort" icons in "my videos"
  frontend/src/routes/manage/Video/index.tsx
Labels: changelog:user

#525 Improve thumbnail fallback and playing indicator
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Video.tsx
Labels: changelog:user

#532 Add ability to show series description in series block (plus various other things)
  backend/src/api/model/block/mod.rs
  backend/src/api/model/block/mutations.rs
  backend/src/api/mutation.rs
  backend/src/db/cmd.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/13-series-block-show-metadata.sql
  backend/src/http/handlers.rs
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/Content/AddButtons.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Series.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Text.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Title.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/index.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/util.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/util/video.ts
  frontend/src/util/video.tsx
Labels: changelog:user, changelog:dev

#534 Fix `mountSeries` mounting into existing realms
  backend/src/api/mutation.rs
Labels: changelog:dev

#535 Add build script commands to bring containers down + remove volumes
  x.sh
Labels: changelog:dev
