Repository elan-ev/tobira, pull requests merged in 2022-11, with the labels that each got.

#577 Improve some configuration things
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/cmd/check.rs
  backend/src/config/general.rs
  backend/src/config/mod.rs
  backend/src/config/theme.rs
  backend/src/http/assets.rs
  docs/docs/setup/config.toml
Labels: changelog:admin

#574 Search on pressing enter
  frontend/src/layout/header/Search.tsx
Labels: changelog:user

#578 Make Tobira properly handle multi-quality HLS streams
  backend/src/api/model/event.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/16-master-track.sql
  backend/src/db/types.rs
  backend/src/sync/harvest/response.rs
  frontend/src/routes/Embed.tsx
  frontend/src/routes/Video.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/player/Paella.tsx
  frontend/src/ui/player/index.tsx
Labels: changelog:user

#580 Check version of `rustc` and `npm` in `x.sh`
  util/scripts/check-system.sh
Labels: changelog:dev

#579 Improve GraphQL API HTTP handling code
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/api/err.rs
  backend/src/auth/handlers.rs
  backend/src/db/tx.rs
  backend/src/http/handlers.rs
  backend/src/http/response.rs
Labels: changelog:dev

#582 Provide DB dump with useful data and use it for CI checks, deployment, and DX
  .deployment/deploy.yml
  .deployment/remove-deployment.yml
  .deployment/setup-server.yml
  .github/workflows/build-release.yml
  .github/workflows/ci.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/deploy.yml
  .github/workflows/remove-deployment.yml
  .github/workflows/upload-db-dump.yml
  util/scripts/db-load-dump.sh
  x.sh
Labels: changelog:dev

#588 Update dependencies in `docs/` to resolve some audit warnings
  docs/package-lock.json
  docs/package.json
Labels: kind:documentation, dependencies, changelog:dev

#591 Disable request buffering in our CORS proxy
  util/containers/opencast-cors-proxy-nginx.conf
Labels: kind:bug, area:infrastructure, changelog:dev

#592 JWT expiry during upload should no longer be a problem under normal circumstances
  .deployment/templates/config.toml
  docs/docs/setup/jwt.md
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Upload.tsx
Labels: kind:documentation, area:frontend, kind:improvement, area:infrastructure, changelog:admin

#597 Add `--dummy-blocks` to `import-realm-tree` when creating DB dump
  .github/workflows/upload-db-dump.yml
Labels: changelog:dev

#598 Add docs about "updating Tobira" and "resync"
  docs/docs/setup/resync.md
  docs/docs/setup/update.md
Labels: changelog:admin

#602 Fix DB migration deadlock by acquiring exclusive lock first
  backend/src/db/migrations.rs
Labels: changelog:admin

#596 Small improvements of the video page
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Search.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/metadata.tsx
  frontend/src/util/video.tsx
Labels: changelog:user

#607 Avoid host networking
  util/containers/docker-compose.yml
  util/containers/opencast-cors-proxy-nginx.conf
  util/containers/tobira-auth-proxy-nginx.conf
  util/dev-config/config.toml
Labels: kind:improvement, area:infrastructure

#605 Add versioned docs
  .github/workflows/deploy-docs.yml
  docs/.gitignore
  docs/README.md
  docs/docusaurus.config.js
  docs/versions.txt
  util/scripts/build-versioned-docs.sh
  util/scripts/clean-versioned-docs.sh
  util/scripts/make-release.sh
Labels: changelog:admin

#608 Fix building Tobira on macOS
  backend/Cargo.toml
  backend/src/metrics.rs
  util/scripts/check-system.sh
  util/scripts/on-backend-change.sh
Labels: changelog:dev

#609 Add `--color` flag to configure color choice and default to 'auto'
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/args.rs
  backend/src/cmd/check.rs
  backend/src/logger.rs
  backend/src/main.rs
Labels: changelog:admin

#612 Fix `tobira check` for empty search index
  backend/src/cmd/check.rs
  backend/src/search/meta.rs
Labels: changelog:admin
