Repository elan-ev/tobira, pull requests merged in 2022-10, with the labels that each got.

#553 Doc improvements
  docs/docs/setup/ansible-example.md
  docs/docs/setup/auth/index.md
  docs/docusaurus.config.js
Labels: kind:documentation, area:ci, kind:improvement, changelog:admin

#554 Fix and improve `db clear` (and related) subcommands
  backend/src/db/cmd.rs
  backend/src/search/writer.rs
  backend/src/sync/cmd.rs
Labels: area:backend, kind:bug, kind:improvement, changelog:admin

#557 Generate embed codes for Tobira directly instead of for the Opencast player
  frontend/src/App.tsx
  frontend/src/GlobalStyle.tsx
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/MenuState.tsx
  frontend/src/layout/Root.tsx
  frontend/src/rauta.tsx
  frontend/src/router.tsx
  frontend/src/routes/Embed.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/Content/index.tsx
  frontend/src/routes/util.tsx
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/player/index.tsx
  frontend/src/util/err.tsx
  frontend/src/util/index.ts
  util/fixtures.sql
Labels: changelog:user

#552 Check for changes to APIs used by the admin UI integraiton in PRs
  .github/workflows/check-admin-ui-api.yml
  .github/workflows/check-admin-ui-api/onComplete.js
  .github/workflows/check-admin-ui-api/rule.js
Labels: area:ci, kind:new-feature, changelog:dev

#572 Fix `/~metrics` endpoint for PG14 and PG15
  backend/src/metrics.rs
Labels: changelog:admin
