Repository elan-ev/tobira, pull requests merged in 2023-09, with the labels that each got.

#931 Switch to GitHub LFS for DB dumps
  .deployment/deploy.yml
  .github/workflows/ci.yml
  .github/workflows/upload-db-dump.yml
  util/scripts/db-load-dump.sh
Labels: changelog:dev

#929 Replace `atty` dependency with `std::io::IsTerminal`
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/args.rs
Labels: changelog:nope

#925 Remove highlight when clicking external studio link
  frontend/src/ui/index.tsx
Labels: changelog:user

#928 Add return label to studio link
  frontend/src/layout/header/UserBox.tsx
  frontend/src/relay/auth.tsx
  frontend/src/routes/manage/index.tsx
Labels: changelog:user

#926 Add optional link to video page for video blocks
  backend/src/api/model/block/mod.rs
  backend/src/api/model/block/mutations.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/23-video-block-show-link.sql
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/manage/Realm/Content/AddButtons.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/Blocks/index.tsx
Labels: changelog:user

#930 Clean up translations
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/Navigation.tsx
  frontend/src/layout/Root.tsx
  frontend/src/layout/header/UserBox.tsx
  frontend/src/layout/header/index.tsx
  frontend/src/routes/About.tsx
  frontend/src/routes/Login.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/ChildOrder.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/index.tsx
  frontend/src/routes/manage/Realm/General.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/ui/Breadcrumbs.tsx
  frontend/src/ui/Modal.tsx
  frontend/src/ui/SearchableSelect.tsx
  frontend/src/ui/player/index.tsx
  frontend/src/ui/time.tsx
Labels: changelog:nope

#933 Update dependencies
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/sync/status.rs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/util/err.tsx
Labels: changelog:nope

#936 Replace most Hero icons by ones from Lucide
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/ui/Video.tsx
Labels: changelog:nope

#943 Add "start at:" option to share menu
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Embed.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/typings/paella-core.d.ts
  frontend/src/ui/Input.tsx
  frontend/src/ui/player/Paella.tsx
  frontend/src/ui/player/PlayerContext.tsx
  frontend/src/util/index.ts
Labels: changelog:user

#949 Add player context to video blocks
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/player/index.tsx
Labels: changelog:user

#947 Add UI for creating/modifying ACLs and include it in uploader
  backend/src/api/model/event.rs
  backend/src/api/model/user.rs
  frontend/src/User.tsx
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/relay/boundary.tsx
  frontend/src/router.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/manage/Video/Access.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Access.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Button.tsx
  frontend/src/ui/FloatingBaseMenu.tsx
  frontend/src/ui/SearchableSelect.tsx
  frontend/src/util/roles.tsx
  util/containers/opencast-cors-proxy-nginx.conf
Labels: changelog:user

#938 Add new Paella skin
  backend/src/http/assets.rs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/typings/paella-core.d.ts
  frontend/src/ui/player/Paella.tsx
  frontend/webpack.config.ts
Labels: changelog:user
