Repository elan-ev/tobira, pull requests merged in 2023-08, with the labels that each got.

#868 Add playwright e2e tests
  .github/workflows/ci.yml
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/playwright.config.ts
  frontend/tests/blocks.spec.ts
  frontend/tests/common.ts
  frontend/tests/languageSelection.spec.ts
  frontend/tests/login.spec.ts
  frontend/tests/realms.spec.ts
  frontend/tests/search.spec.ts
  frontend/tests/videoPage.spec.ts
  frontend/tsconfig.json
Labels: changelog:dev

#912 Reduce log noise when the `/tobira/stats` endpoint does not exist in OC
  backend/src/sync/client.rs
  backend/src/sync/stats.rs
Labels: changelog:admin

#917 Fix failing video page test for master deployments
  frontend/tests/videoPage.spec.ts
Labels: changelog:nope

#919 Fix cut-off thumbails on vertically narrow screens
  frontend/src/ui/player/index.tsx
Labels: changelog:user

#913 Change debug info to "line-tables-only"
  backend/Cargo.toml
  util/scripts/check-system.sh
Labels: changelog:dev

#915 Add scrollbar to multiline copyable inputs
  frontend/src/ui/Input.tsx
Labels: changelog:user

#916 Close burger menu when clicking specific items
  frontend/src/routes/Realm.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/ui/index.tsx
Labels: changelog:user

#896 Increase dashboad coherence
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/Burger.tsx
  frontend/src/layout/header/UserBox.tsx
  frontend/src/routes/Realm.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/routes/manage/Video/TechnicalDetails.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/ui/index.tsx
Labels: changelog:user

#922 Some low hanging dependency updates
  frontend/package-lock.json
  frontend/package.json
  frontend/src/i18n/index.ts
  frontend/src/util/index.ts
Labels: area:frontend, kind:improvement, dependencies, javascript, changelog:nope
