Repository elan-ev/tobira, pull requests merged in 2023-01, with the labels that each got.

#653 Update backend dependencies
  backend/Cargo.lock
  backend/src/sync/client.rs
Labels: area:backend, dependencies

#644 Improve contrast between some texts and their backgrounds
  backend/src/config/color.rs
  frontend/src/ui/Blocks/Series.tsx
Labels: changelog:user, area:accessibility

#662 Apply hover styles also on keyboard focus
  frontend/src/GlobalStyle.tsx
  frontend/src/layout/header/Search.tsx
  frontend/src/layout/header/UserBox.tsx
  frontend/src/layout/header/ui.tsx
  frontend/src/routes/Search.tsx
  frontend/src/routes/manage/Realm/ChildOrder.tsx
  frontend/src/routes/manage/Realm/Content/AddButtons.tsx
  frontend/src/routes/manage/Realm/Content/Edit/RemoveButton.tsx
  frontend/src/routes/manage/Realm/Content/util.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/ui/Button.tsx
  frontend/src/ui/index.tsx
Labels: changelog:user

#645 Add framework for authentication (authkit) and use it for local dev setup & test deployments
  .deployment/deploy.yml
  .deployment/setup-server.yml
  .deployment/templates/tobiraauth.service
  .github/workflows/check-authkit.yml
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/auth/handlers.rs
  backend/src/auth/mod.rs
  backend/src/http/handlers.rs
  backend/src/http/response.rs
  backend/src/sync/client.rs
  backend/src/util.rs
  docs/docs/setup/auth/example-all-own.md
  docs/docs/setup/auth/example-all-tobira.md
  docs/docs/setup/auth/full-auth-proxy.md
  docs/docs/setup/auth/in-depth.md
  docs/docs/setup/auth/index.md
  docs/docs/setup/auth/jwt.md
  docs/docs/setup/auth/login-page.md
  docs/docs/setup/auth/login-proxy.md
  docs/docs/setup/auth/session-management.md
  docs/docs/setup/auth/user.md
  util/authkit/.gitignore
  util/authkit/README.md
  util/authkit/package-lock.json
  util/authkit/package.json
  util/authkit/src/index.ts
  util/authkit/tsconfig.json
  util/containers/docker-compose.yml
  util/containers/login-handler.py
  util/containers/tobira-auth-proxy-nginx.conf
  util/dummy-login/.gitignore
  util/dummy-login/README.md
  util/dummy-login/dist/index.js
  util/dummy-login/index.ts
  util/dummy-login/package-lock.json
  util/dummy-login/package.json
  util/dummy-login/tsconfig.json
Labels: changelog:admin

#664 Make Tobira work with PostgreSQL schemas other than `public`
  backend/src/db/cmd.rs
  backend/src/db/query.rs
  docs/docs/setup/requirements.md
Labels: changelog:admin

#655 Make events findable via opencastId
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/api/model/search/mod.rs
Labels: area:search, changelog:user

#685 Fix minor frontend bugs
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Button.tsx
Labels: changelog:user

#686 Reduce noisiness of harvest logging
  backend/src/prelude.rs
  backend/src/sync/client.rs
  backend/src/sync/harvest/mod.rs
Labels: changelog:admin

#687 Update `bobheadxi/deployments` to v1.4 to properly delete old GH envs
  .github/workflows/remove-deployment.yml
Labels: changelog:nope

#689 Fix `remove-deployment` action
  .github/workflows/remove-deployment.yml
Labels: changelog:nope

#688 Improve presentation order of upcoming and live events
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Video.tsx
Labels: changelog:user

#633 Add cancel button to video uploader and also cancel upload when leaving route
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Upload.tsx
Labels: changelog:user

#697 Fix and improve release script
  util/scripts/make-release.sh
Labels: changelog:dev
