Repository elan-ev/tobira, pull requests merged in 2023-10, with the labels that each got.

#962 Unify focus style on miscellaneous elements
  frontend/src/App.tsx
  frontend/src/layout/Footer.tsx
  frontend/src/layout/header/UserBox.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/ui/Blocks/Text.tsx
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/Breadcrumbs.tsx
Labels: changelog:user, area:accessibility

#964 Do not include `"email": null` in JWT (if there is no email)
  backend/src/auth/jwt.rs
Labels: changelog:admin

#963 Add configurable known groups
  .deployment/deploy.yml
  .deployment/files/known-groups.json
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/api/mod.rs
  backend/src/api/model/known_roles.rs
  backend/src/api/model/mod.rs
  backend/src/api/query.rs
  backend/src/api/util.rs
  backend/src/args.rs
  backend/src/cmd/known_groups.rs
  backend/src/cmd/mod.rs
  backend/src/db/cmd.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/24-known-groups.sql
  backend/src/http/mod.rs
  backend/src/main.rs
  docs/docs/setup/config.md
  docs/docs/setup/requirements.md
  frontend/relay.config.js
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Upload.tsx
  frontend/src/routes/manage/Video/Access.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Access.tsx
  util/dummy-login/dist/index.js
  util/dummy-login/index.ts
Labels: changelog:breaking

#978 `cargo update`
  backend/Cargo.lock
Labels: dependencies, changelog:dev
