Repository elan-ev/tobira, pull requests merged in 2023-11, with the labels that each got.

#981 Add utility functions for building GraphQL event and series IDs
  frontend/src/routes/Embed.tsx
  frontend/src/routes/Search.tsx
  frontend/src/routes/Series.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Video/Access.tsx
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/routes/manage/Video/TechnicalDetails.tsx
  frontend/src/util/index.ts
Labels: changelog:dev

#980 Replace manual DOM ids with "useId()" hook
  frontend/src/routes/Login.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/manage/Realm/AddChild.tsx
  frontend/src/routes/manage/Realm/General.tsx
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/ui/SearchableSelect.tsx
  frontend/src/ui/metadata.tsx
Labels: changelog:nope

#983 Retain volume setting across all videos
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user

#985 Fix paella dual stream layout
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user

#986 Change type of event duration in DB from i32 to i64
  backend/src/api/model/event.rs
  backend/src/api/model/search/event.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/25-longer-videos.sql
  backend/src/db/tests/util.rs
  backend/src/search/event.rs
  backend/src/sync/harvest/response.rs
  frontend/src/schema.graphql
Labels: changelog:dev

#987 Adjust some translations
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
Labels: changelog:user

#992 Stop radio buttons from shrinking
  frontend/src/routes/manage/Realm/ChildOrder.tsx
  frontend/src/routes/manage/Realm/General.tsx
Labels: changelog:user

#984 Adjust Paella scaling and background
  frontend/src/routes/Video.tsx
  frontend/src/ui/player/Paella.tsx
  frontend/src/ui/player/index.tsx
Labels: changelog:user

#994 Replace feather icons with lucide icons
  frontend/src/layout/Navigation.tsx
  frontend/src/layout/header/UserBox.tsx
  frontend/src/layout/header/index.tsx
  frontend/src/routes/Embed.tsx
  frontend/src/routes/Login.tsx
  frontend/src/routes/NotFound.tsx
  frontend/src/routes/Realm.tsx
  frontend/src/routes/Search.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/ChildOrder.tsx
  frontend/src/routes/manage/Realm/Content/AddButtons.tsx
  frontend/src/routes/manage/Realm/Content/Edit/MoveButtons.tsx
  frontend/src/routes/manage/Realm/Content/Edit/RemoveButton.tsx
  frontend/src/routes/manage/Realm/Content/Edit/index.tsx
  frontend/src/routes/manage/Realm/Content/index.tsx
  frontend/src/routes/manage/Realm/index.tsx
  frontend/src/routes/manage/Video/Access.tsx
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/ui/Access.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/Breadcrumbs.tsx
  frontend/src/ui/Card.tsx
  frontend/src/ui/FloatingBaseMenu.tsx
  frontend/src/ui/Input.tsx
  frontend/src/ui/Modal.tsx
  frontend/src/ui/Video.tsx
  frontend/src/ui/Waiting.tsx
  frontend/src/ui/player/index.tsx
Labels: changelog:nope

#959 Add series rss feed to share button
  .deployment/templates/config.toml
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/config/general.rs
  backend/src/db/types.rs
  backend/src/http/handlers.rs
  backend/src/http/response.rs
  backend/src/main.rs
  backend/src/rss.rs
  docs/docs/setup/config.toml
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Video.tsx
  util/dev-config/config.toml
Labels: changelog:user

#995 Add contextual video link to "referencing pages"
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/manage/Video/Details.tsx
Labels: changelog:user

#1000 Improve error message in case `sync.{user/password}` are incorrect
  backend/src/sync/client.rs
Labels: changelog:admin

#999 Bump MeiliSearch to 1.4, improve ranking and fix `audioOnly` field
  .deployment/setup-server.yml
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/api/model/search/event.rs
  backend/src/api/model/search/mod.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/26-more-event-search-data.sql
  backend/src/search/event.rs
  backend/src/search/mod.rs
  docs/docs/setup/ansible-example.md
  docs/docs/setup/requirements.md
  frontend/src/routes/Search.tsx
  frontend/src/schema.graphql
  util/containers/docker-compose.yml
Labels: changelog:breaking

#997 Forward `ExternalLink` component ref
  frontend/src/relay/auth.tsx
Labels: changelog:dev

#1019 Remove timestamp and download menu from livestreams
  frontend/src/routes/Video.tsx
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user
