Repository elan-ev/tobira, pull requests merged in 2023-12, with the labels that each got.

#935 Add docs with general info about Tobira
  docs/docs/dev/index.md
  docs/docs/semantics.md
  docs/docs/setup/index.md
  docs/docs/ui-elements.png
Labels: changelog:admin

#1002 Drop support for PG11 (bump minimum required version to 12)
  .github/workflows/ci.yml
  docs/docs/setup/requirements.md
Labels: changelog:breaking, changelog:admin

#1030 Hide information on "add child" page behind tooltips
  frontend/src/routes/manage/Realm/AddChild.tsx
Labels: changelog:user

#1041 Update Paella and improve cursor
  frontend/package-lock.json
  frontend/package.json
Labels: changelog:user

#1025 Revise search page design
  backend/src/api/model/known_roles.rs
  backend/src/api/model/search/event.rs
  backend/src/api/model/search/mod.rs
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/header/Search.tsx
  frontend/src/rauta.tsx
  frontend/src/routes/Search.tsx
  frontend/src/schema.graphql
  frontend/tests/search.spec.ts
Labels: changelog:user

#1043 Fix duplicates in user search
  backend/src/api/model/known_roles.rs
  backend/src/api/model/search/mod.rs
  frontend/src/schema.graphql
  frontend/src/ui/Access.tsx
Labels: changelog:nope
