Repository elan-ev/tobira, pull requests merged in 2023-04, with the labels that each got.

#766 Minor improvements to logging
  backend/src/api/model/realm/mutations.rs
  backend/src/http/handlers.rs
  backend/src/prelude.rs
  backend/src/util.rs
  util/dev-config/config.toml
Labels: changelog:admin

#773 Add focus trap to popup modals
  frontend/package-lock.json
  frontend/package.json
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/index.tsx
  frontend/src/routes/manage/Realm/Content/Edit/RemoveButton.tsx
  frontend/src/routes/manage/Realm/DangerZone.tsx
  frontend/src/ui/Modal.tsx
Labels: area:accessibility

#772 Apply redesign of `~manage/realm/` pages
  frontend/src/GlobalStyle.tsx
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/manage/Realm/AddChild.tsx
  frontend/src/routes/manage/Realm/ChildOrder.tsx
  frontend/src/routes/manage/Realm/Content/AddButtons.tsx
  frontend/src/routes/manage/Realm/Content/Block.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Title.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/index.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/util.tsx
  frontend/src/routes/manage/Realm/Content/Edit/index.tsx
  frontend/src/routes/manage/Realm/Content/index.tsx
  frontend/src/routes/manage/Realm/General.tsx
  frontend/src/routes/manage/Realm/index.tsx
  frontend/src/ui/Button.tsx
  frontend/src/ui/Floating.tsx
  frontend/src/ui/Input.tsx
  frontend/src/ui/PathSegmentInput.tsx
Labels: area:design, area:accessibility

#781 Update backend dependencies
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/api/common.rs
  backend/src/auth/handlers.rs
  backend/src/auth/jwt.rs
  backend/src/auth/mod.rs
  backend/src/auth/session_id.rs
  backend/src/db/mod.rs
  backend/src/main.rs
  backend/src/metrics.rs
  backend/src/sync/client.rs
Labels: changelog:admin

#783 Drop PostgreSQL 10 support and fix user session query
  .github/workflows/ci.yml
  backend/src/auth/mod.rs
  util/containers/docker-compose.yml
Labels: changelog:admin

#786 Update reinda via `cargo update`
  backend/Cargo.lock
Labels: changelog:nope

#789 Update MeiliSearch to v1.1
  .deployment/setup-server.yml
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/search/mod.rs
  docs/docs/setup/ansible-example.md
  docs/docs/setup/requirements.md
  util/containers/docker-compose.yml
Labels: changelog:admin

#787 Add remaining dashboard items to user menu
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/header/UserBox.tsx
  frontend/src/relay/auth.tsx
  frontend/src/routes/manage/index.tsx
Labels: changelog:user

#790 Fix edit form of series blocks
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Series.tsx
Labels: changelog:user
