Repository elan-ev/tobira, pull requests merged in 2023-03, with the labels that each got.

#728 Fix breadcrumbs for realms with missing names & correctly type JSON-LD objects
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Realm.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/AddChild.tsx
  frontend/src/routes/manage/Realm/Content/index.tsx
  frontend/src/routes/manage/Realm/index.tsx
  frontend/src/ui/Breadcrumbs.tsx
  frontend/src/util/realm.tsx
Labels: changelog:user

#729 Use searchable series select in series block edit UI
  backend/src/api/model/search/mod.rs
  backend/src/api/model/series.rs
  backend/src/api/query.rs
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Series.tsx
  frontend/src/routes/manage/Realm/Content/index.tsx
  frontend/src/schema.graphql
  frontend/src/ui/SearchableSelect.tsx
Labels: changelog:user

#730 Improve API error handling
  backend/src/api/err.rs
  backend/src/db/tx.rs
  backend/src/http/handlers.rs
  frontend/src/relay/boundary.tsx
Labels: changelog:dev

#708 Use `React.StrictMode` and type-safe translation keys with i18next
  .github/workflows/ci.yml
  docs/docs/dev/build/dev.md
  frontend/.eslintrc.js
  frontend/constants.js
  frontend/package-lock.json
  frontend/package.json
  frontend/relay.config.js
  frontend/src/App.tsx
  frontend/src/i18n/.gitignore
  frontend/src/rauta.tsx
  frontend/src/routes/Login.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/manage/Realm/AddChild.tsx
  frontend/src/routes/manage/Realm/Content/Block.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
  frontend/src/routes/manage/Realm/Content/Edit/index.tsx
  frontend/src/routes/manage/Realm/util.tsx
  frontend/src/typings/i18next.d.ts
  frontend/src/ui/LoadingIndicator.tsx
  frontend/src/ui/SearchableSelect.tsx
  frontend/src/util/err.tsx
  frontend/tsconfig.json
  frontend/webpack.config.ts
Labels: changelog:dev

#738 Disable `spellcheck` and `autocapitalize` on username and path inputs
  frontend/src/routes/Login.tsx
  frontend/src/ui/PathSegmentInput.tsx
Labels: changelog:user

#737 Improve "gallery view" of series block
  frontend/src/ui/Blocks/Series.tsx
Labels: changelog:user

#727 Add user realms (a page tree for each user)
  backend/src/api/context.rs
  backend/src/api/err.rs
  backend/src/api/model/block/mutations.rs
  backend/src/api/model/realm/mod.rs
  backend/src/api/model/realm/mutations.rs
  backend/src/api/model/search/mod.rs
  backend/src/api/model/user.rs
  backend/src/api/mutation.rs
  backend/src/api/query.rs
  backend/src/auth/mod.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/18-user-realms.sql
  backend/src/db/migrations/19-series-search-view.sql
  backend/src/db/migrations/20-fix-queue-triggers.sql
  backend/src/search/event.rs
  backend/src/search/realm.rs
  backend/src/search/series.rs
  docs/docs/setup/config.toml
  frontend/src/User.tsx
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/Navigation.tsx
  frontend/src/layout/header/UserBox.tsx
  frontend/src/relay/boundary.tsx
  frontend/src/routes/Realm.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/AddChild.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
  frontend/src/routes/manage/Realm/Content/index.tsx
  frontend/src/routes/manage/Realm/DangerZone.tsx
  frontend/src/routes/manage/Realm/General.tsx
  frontend/src/routes/manage/Realm/index.tsx
  frontend/src/routes/manage/Realm/util.tsx
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/schema.graphql
  frontend/src/ui/SearchableSelect.tsx
Labels: changelog:user

#736 Improve `dummy-blocks` for better test data
  .deployment/files/realms.yaml
  backend/src/cmd/import_realm_tree.rs
  util/dummy-realms.yaml
Labels: kind:improvement
