Repository elan-ev/tobira, pull requests merged in 2023-05, with the labels that each got.

#796 Rework colors and add experimental dark mode
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/config/color.rs
  backend/src/config/mod.rs
  backend/src/config/theme.rs
  backend/src/http/handlers.rs
  backend/src/main.rs
  docs/docs/setup/config.toml
  frontend/src/App.tsx
  frontend/src/GlobalStyle.tsx
  frontend/src/color.tsx
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/index.html
  frontend/src/layout/Burger.tsx
  frontend/src/layout/Footer.tsx
  frontend/src/layout/Navigation.tsx
  frontend/src/layout/header/Logo.tsx
  frontend/src/layout/header/Search.tsx
  frontend/src/layout/header/UserBox.tsx
  frontend/src/layout/header/index.tsx
  frontend/src/layout/header/ui.tsx
  frontend/src/relay/boundary.tsx
  frontend/src/routes/Login.tsx
  frontend/src/routes/Realm.tsx
  frontend/src/routes/Search.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/AddChild.tsx
  frontend/src/routes/manage/Realm/ChildOrder.tsx
  frontend/src/routes/manage/Realm/Content/AddButtons.tsx
  frontend/src/routes/manage/Realm/Content/Block.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/util.tsx
  frontend/src/routes/manage/Realm/Content/Edit/RemoveButton.tsx
  frontend/src/routes/manage/Realm/Content/index.tsx
  frontend/src/routes/manage/Realm/Content/util.tsx
  frontend/src/routes/manage/Realm/DangerZone.tsx
  frontend/src/routes/manage/Realm/General.tsx
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/routes/manage/Video/TechnicalDetails.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Blocks/Text.tsx
  frontend/src/ui/Breadcrumbs.tsx
  frontend/src/ui/Button.tsx
  frontend/src/ui/Card.tsx
  frontend/src/ui/Floating.tsx
  frontend/src/ui/Input.tsx
  frontend/src/ui/LoadingIndicator.tsx
  frontend/src/ui/Modal.tsx
  frontend/src/ui/PathSegmentInput.tsx
  frontend/src/ui/SearchableSelect.tsx
  frontend/src/ui/Spinner.tsx
  frontend/src/ui/Video.tsx
  frontend/src/ui/index.tsx
  frontend/src/ui/metadata.tsx
  frontend/src/ui/player/index.tsx
  frontend/src/util/err.tsx
  frontend/src/util/index.ts
Labels: changelog:user

#798 Fix audio-only playablility
  frontend/src/typings/paella-core.d.ts
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user

#813 Add docs (configuring the theme & various information for devs)
  backend/src/config/color.rs
  backend/src/config/mod.rs
  backend/src/config/theme.rs
  docs/docs/dev/create-release.md
  docs/docs/dev/various-info.md
  docs/docs/img/logo-margin.png
  docs/docs/setup/config.md
  docs/docs/setup/config.toml
  docs/docs/setup/theme.md
Labels: changelog:admin

#792 Improvements to video page
  backend/src/config/general.rs
  backend/src/http/assets.rs
  docs/docs/setup/config.toml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/config.ts
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/index.html
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Video/TechnicalDetails.tsx
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/Button.tsx
  frontend/src/ui/Floating.tsx
  frontend/src/ui/Modal.tsx
  frontend/src/ui/metadata.tsx
  frontend/src/ui/player/Paella.tsx
  frontend/src/ui/player/index.tsx
  frontend/src/ui/time.tsx
Labels: changelog:user

#812 Enable backtraces for errors
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/main.rs
Labels: changelog:admin

#811 Underline specific kinds of links
  frontend/src/GlobalStyle.tsx
  frontend/src/layout/header/UserBox.tsx
  frontend/src/routes/Login.tsx
  frontend/src/routes/Search.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Breadcrumbs.tsx
  frontend/src/ui/Button.tsx
  frontend/src/ui/index.tsx
Labels: changelog:user, area:accessibility

#817 Fix paella player errors in log & update Paella to 1.31.2
  frontend/package-lock.json
  frontend/package.json
  frontend/src/ui/player/Paella.tsx
Labels: changelog:nope

#818 Add redirect from video routes to direct video routes if realm does not exist
  frontend/src/routes/Video.tsx
Labels: changelog:user

#819 Rearrange dashboard items
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/header/UserBox.tsx
  frontend/src/routes/manage/index.tsx
Labels: changelog:user

#820 Make JWT key optional by generating it on the fly if unspecified
  backend/src/auth/jwt.rs
  backend/src/auth/mod.rs
  backend/src/cmd/check.rs
  backend/src/config/mod.rs
  docs/docs/setup/ansible-example.md
  docs/docs/setup/auth/index.md
  docs/docs/setup/auth/jwt.md
  docs/docs/setup/config.toml
  docs/docs/setup/deploy.md
  docs/docs/setup/requirements.md
Labels: changelog:admin

#821 Update dependencies
  backend/Cargo.lock
  frontend/package-lock.json
  frontend/package.json
Labels: area:backend, area:frontend, dependencies, changelog:dev

#774 Add current language to language selection label
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/header/UserBox.tsx
Labels: changelog:user

#824 Adjust some borders of user menu items
  frontend/src/layout/header/UserBox.tsx
Labels: changelog:user

#830 Fix `CopyableInput` and header button color in Safari
  frontend/src/layout/header/ui.tsx
  frontend/src/ui/Input.tsx
Labels: changelog:user

#837 Fix margin around user realm disclaimer on narrow screens
  frontend/src/routes/Realm.tsx
Labels: changelog:user

#851 Fix tooltips not opening on mobile
  frontend/src/ui/Floating.tsx
Labels: changelog:user

#860 Fix setting a derived realm name for user root realms
  backend/src/db/migrations.rs
  backend/src/db/migrations/21-fix-user-root-realm-name-block.sql
Labels: changelog:user

#853 Adjust metadata and description layout
  frontend/src/routes/Video.tsx
Labels: changelog:user

#861 Fix `import-realm-tree` command
  backend/src/cmd/import_realm_tree.rs
Labels: changelog:dev
