Repository elan-ev/tobira, pull requests merged in 2023-06, with the labels that each got.

#866 Fix two bugs with the relay store
  frontend/src/routes/manage/Realm/AddChild.tsx
  frontend/src/routes/manage/Realm/index.tsx
Labels: changelog:user

#823 Update frontend dependencies
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies, changelog:nope

#876 Use shared ESLint config
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/global.d.ts
  frontend/src/rauta.tsx
  frontend/src/relay/errors.ts
  frontend/src/routes/manage/Realm/Content/Edit/index.tsx
  frontend/src/ui/index.tsx
  frontend/src/util/index.ts
Labels: changelog:dev

#871 Fix dark mode problems
  .deployment/deploy.yml
  .deployment/templates/config.toml
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  backend/src/cmd/check.rs
  backend/src/config/color.rs
  backend/src/config/mod.rs
  backend/src/config/theme.rs
  backend/src/http/assets.rs
  docs/docs/dev/various-info.md
  docs/docs/setup/ansible-example.md
  docs/docs/setup/config.toml
  docs/docs/setup/theme.md
  frontend/src/GlobalStyle.tsx
  frontend/src/config.ts
  frontend/src/index.html
  frontend/src/layout/header/Logo.tsx
  frontend/src/layout/header/Search.tsx
  frontend/src/layout/header/UserBox.tsx
  frontend/src/layout/header/index.tsx
  frontend/src/routes/Login.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/ChildOrder.tsx
  frontend/src/routes/manage/Realm/Content/AddButtons.tsx
  frontend/src/routes/manage/Realm/Content/util.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Modal.tsx
  frontend/src/ui/SearchableSelect.tsx
  frontend/src/ui/Video.tsx
  frontend/src/ui/index.tsx
  frontend/src/ui/metadata.tsx
  frontend/src/ui/player/index.tsx
  frontend/src/util/err.tsx
  util/dev-config/config.toml
  util/dev-config/logo-large-dark.svg
Labels: changelog:user

#888 Correct quantity wording for uploads
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
Labels: changelog:user

#887 Mark series field as required for upload
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Upload.tsx
  frontend/src/ui/metadata.tsx
Labels: changelog:user

#889 Change default font of copyable input
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/routes/manage/Video/TechnicalDetails.tsx
  frontend/src/ui/Input.tsx
Labels: changelog:user

#890 Fix "redirect after external login"
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/index.tsx
  frontend/src/routes/Login.tsx
Labels: changelog:user

#891 Show warning when clicking outside editing block
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/index.tsx
Labels: changelog:user

#892 Close QR-modal on outside click
  frontend/src/routes/Video.tsx
  frontend/src/ui/Floating.tsx
  frontend/src/ui/Modal.tsx
Labels: changelog:user

#894 Fix error text color
  frontend/src/util/err.tsx
Labels: changelog:user
