Repository elan-ev/tobira, pull requests merged in 2024-03, with the labels that each got.

#1125 Update frontend dependencies
  frontend/package-lock.json
  frontend/package.json
  frontend/relay.config.js
  frontend/src/layout/Navigation.tsx
  frontend/src/relay/index.ts
  frontend/src/routes/Search.tsx
  frontend/src/routes/Series.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
  frontend/src/routes/manage/Realm/General.tsx
  frontend/src/routes/manage/Realm/index.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/routes/manage/Video/TechnicalDetails.tsx
  frontend/src/routes/util.tsx
  frontend/src/ui/Access.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/SearchableSelect.tsx
  frontend/src/ui/Video.tsx
  frontend/src/ui/metadata.tsx
  frontend/src/ui/player/Paella.tsx
  frontend/src/ui/player/index.tsx
  frontend/src/util/index.ts
  frontend/src/util/realm.tsx
  frontend/src/util/video.tsx
Labels: changelog:nope

#1093 Improve UI tests by running each in isolation (separate Tobira process & DB) with fixed offline data
  .gitattributes
  .github/workflows/ci.yml
  backend/src/db/cmd.rs
  docs/docs/dev/create-release.md
  docs/docs/dev/tests.md
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/playwright.config.ts
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/manage/Realm/General.tsx
  frontend/tests/blocks.spec.ts_
  frontend/tests/common.ts
  frontend/tests/empty.spec.ts
  frontend/tests/fixtures/standard.sql
  frontend/tests/languageSelection.spec.ts
  frontend/tests/login.spec.ts
  frontend/tests/realms.spec.ts
  frontend/tests/search.spec.ts
  frontend/tests/tsconfig.json
  frontend/tests/util/common.ts
  frontend/tests/util/data.ts
  frontend/tests/util/isolation.ts
  frontend/tests/util/realm.ts
  frontend/tests/util/user.ts
  frontend/tests/videoPage.spec.ts
  util/containers/docker-compose.yml
  util/containers/test-files/cat-black-x264-144p.mp4
  util/containers/test-files/cat-black-x264-240p.mp4
  util/containers/test-files/cat-bokeh-no-audio-x264-144p.mp4
  util/containers/test-files/cat-bokeh-no-audio-x264-240p.mp4
  util/containers/test-files/scifi-tunnel-no-audio-x264-144p.mp4
  util/containers/test-files/thumbnail-cat.jpg
  util/containers/test-files/thumbnail-cat2.jpg
  util/containers/test-files/thumbnail-train.jpg
  util/containers/test-files/train-portrait-x264.mp4
  util/containers/ui-test-files-nginx.conf
Labels: changelog:dev

#1134 Fix bug of event search not returning writable events for ROLE_ADMIN
  backend/src/api/model/search/mod.rs
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/manage/Realm/AddChild.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Series.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
  frontend/src/ui/index.tsx
  frontend/tests/fixtures/standard.sql
  frontend/tests/login.spec.ts
  frontend/tests/search.spec.ts
  frontend/tests/util/user.ts
Labels: changelog:user

#1135 Use secret password for `admin` user on test deployment
  .deployment/deploy.yml
  .deployment/templates/config.toml
  .deployment/templates/tobiraauth.service
  .github/workflows/deploy.yml
  util/dummy-login/dist/index.js
  util/dummy-login/index.ts
Labels: changelog:dev

#1136 Improve screen reader accessibility
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/manage/Video/index.tsx
Labels: changelog:user

#1138 Replace actual ETH test server URL in docs with dummy URL
  docs/docs/setup/matomo.md
Labels: changelog:nope

#1139 Update `paella-user-tracking` to 1.42.1 to fix two bugs
  frontend/package-lock.json
  frontend/package.json
Labels: changelog:admin

#1141 Fix deadlock in auth cache (solves Tobira freezing problem)
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/auth/cache.rs
  backend/src/auth/config.rs
  backend/src/auth/mod.rs
Labels: changelog:admin

#1142 Update `loadtest` utility with new GraphQL requests
  util/loadtest/src/gql_index.json
  util/loadtest/src/gql_video.json
Labels: changelog:dev

#1137 Rework Tobira permission roles: remove "Tobira moderator", add "Tobira admin", add granular roles
  .deployment/templates/config.toml
  backend/src/api/context.rs
  backend/src/api/model/realm/mod.rs
  backend/src/api/model/search/mod.rs
  backend/src/api/model/series.rs
  backend/src/api/model/user.rs
  backend/src/api/query.rs
  backend/src/auth/config.rs
  backend/src/auth/mod.rs
  backend/src/http/assets.rs
  docs/docs/semantics.md
  docs/docs/setup/config.toml
  frontend/src/User.tsx
  frontend/src/config.ts
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/relay/boundary.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Series.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Access.tsx
  frontend/src/util/roles.tsx
  util/dev-config/config.toml
  util/dummy-login/dist/index.js
  util/dummy-login/index.ts
Labels: changelog:breaking

#1145 Improve logging: switch to `tracing` & make filters more powerful
  .deployment/templates/config.toml
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/api/model/block/mutations.rs
  backend/src/api/model/realm/mod.rs
  backend/src/api/model/realm/mutations.rs
  backend/src/cmd/check.rs
  backend/src/db/mod.rs
  backend/src/db/tx.rs
  backend/src/http/handlers.rs
  backend/src/logger.rs
  backend/src/main.rs
  backend/src/prelude.rs
  backend/src/search/cmd.rs
  backend/src/search/mod.rs
  backend/src/sync/client.rs
  backend/src/sync/cmd.rs
  docs/docs/setup/config.toml
  frontend/tests/util/isolation.ts
  util/dev-config/config.toml
Labels: changelog:breaking

#1149 Adjust paella progress bar color
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user

#1144 Add series to search results
  backend/src/api/common.rs
  backend/src/api/model/search/mod.rs
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Search.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Video.tsx
  frontend/tests/search.spec.ts
Labels: changelog:user
