Repository elan-ev/tobira, pull requests merged in 2024-12, with the labels that each got.

#1244 Add support for event specific password protection
  .deployment/templates/config.toml
  .github/workflows/upload-db-dump.yml
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/api/common.rs
  backend/src/api/model/event.rs
  backend/src/api/model/search/event.rs
  backend/src/api/model/search/mod.rs
  backend/src/api/query.rs
  backend/src/auth/mod.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/39-preview-roles-and-credentials.sql
  backend/src/db/types.rs
  backend/src/search/event.rs
  backend/src/search/mod.rs
  backend/src/search/util.rs
  backend/src/sync/harvest/mod.rs
  backend/src/sync/harvest/response.rs
  backend/src/sync/mod.rs
  docs/docs/setup/config.toml
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/header/UserBox.tsx
  frontend/src/routes/Embed.tsx
  frontend/src/routes/Login.tsx
  frontend/src/routes/Search.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/routes/manage/Video/TechnicalDetails.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/Blocks/VideoList.tsx
  frontend/src/ui/Video.tsx
  frontend/src/ui/player/Paella.tsx
  frontend/src/ui/player/index.tsx
  frontend/src/util/index.ts
  util/dev-config/config.toml
Labels: changelog:user

#1272 Make event ACL editable via Tobira
  backend/src/api/err.rs
  backend/src/api/model/acl.rs
  backend/src/api/model/event.rs
  backend/src/api/model/realm/mod.rs
  backend/src/api/model/realm/mutations.rs
  backend/src/api/model/series.rs
  backend/src/api/mutation.rs
  backend/src/auth/mod.rs
  backend/src/config/general.rs
  backend/src/http/assets.rs
  backend/src/sync/client.rs
  docs/docs/setup/config.toml
  frontend/src/config.ts
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/relay/errors.ts
  frontend/src/routes/manage/Video/Access.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Access.tsx
  frontend/src/util/err.tsx
Labels: area:api, changelog:user

#1294 Fix UI tests for search (maybe?)
  frontend/tests/search.spec.ts
Labels: changelog:nope

#1296 Move config sync.{user,password} to opencast.*
  .deployment/templates/config.toml
  backend/src/config/opencast.rs
  backend/src/sync/client.rs
  backend/src/sync/mod.rs
  backend/src/sync/text/mod.rs
  docs/docs/setup/config.toml
  frontend/tests/util/isolation.ts
  util/dev-config/config.toml
Labels: changelog:breaking

#1297 Skip buggy search UI test for firefox
  frontend/tests/search.spec.ts
Labels: changelog:nope

#1298 Update Juniper to 0.16
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/api/common.rs
  backend/src/api/id.rs
  backend/src/api/model/block/mod.rs
  backend/src/api/model/event.rs
  backend/src/api/model/playlist/mod.rs
  backend/src/api/model/realm/mod.rs
  backend/src/api/model/series.rs
  backend/src/api/model/user.rs
  backend/src/api/mutation.rs
  backend/src/api/util.rs
  backend/src/cmd/export_api_schema.rs
  backend/src/http/handlers.rs
  frontend/relay.config.js
  frontend/src/schema.graphql
Labels: changelog:admin

#1302 Update backend dependencies
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/api/model/known_roles.rs
  backend/src/api/model/search/event.rs
  backend/src/api/model/search/mod.rs
  backend/src/api/model/search/realm.rs
  backend/src/api/model/search/series.rs
  backend/src/auth/config.rs
  backend/src/auth/session_id.rs
  backend/src/config/opencast.rs
  backend/src/db/mod.rs
  backend/src/main.rs
  backend/src/search/event.rs
  backend/src/search/mod.rs
  backend/src/sync/client.rs
  backend/src/util.rs
Labels: changelog:admin

#1309 Remove `log.log_http_headers` config and move log calls into submodules
  backend/src/http/handlers.rs
  backend/src/http/log.rs
  backend/src/http/mod.rs
  backend/src/logger.rs
  docs/docs/setup/auth/user/index.md
  docs/docs/setup/config.toml
Labels: changelog:admin
