Repository elan-ev/tobira, pull requests merged in 2024-02, with the labels that each got.

#1089 Add logging of useful DB server information
  backend/src/db/mod.rs
Labels: changelog:admin

#1104 Actually pass relevant options through to `start-dev.sh`
  x.sh
Labels: kind:bug, status:ready, time:minutes, priority:medium, area:build-system, area:auth, changelog:dev

#1097 Add granular permissions to the realm tree
  backend/src/api/model/block/mutations.rs
  backend/src/api/model/realm/mod.rs
  backend/src/api/model/realm/mutations.rs
  backend/src/api/mutation.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/30-realm-permissions.sql
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Realm.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/manage/Realm/AddChild.tsx
  frontend/src/routes/manage/Realm/Content/index.tsx
  frontend/src/routes/manage/Realm/General.tsx
  frontend/src/routes/manage/Realm/RealmPermissions.tsx
  frontend/src/routes/manage/Realm/index.tsx
  frontend/src/routes/manage/Video/Access.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Access.tsx
  frontend/src/ui/Modal.tsx
  frontend/src/util/permissionLevels.tsx
Labels: changelog:user

#1107 Hotfix: realm tree pluralization
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/ui/Access.tsx
Labels: changelog:nope

#1106 Stop using non-existent Roboto fonts in Paella
  frontend/webpack.config.ts
Labels: changelog:dev

#1109 Fix deserialization bugs for `auth.mode = "opencast"` and harvesting in special cases
  backend/src/auth/handlers.rs
  backend/src/sync/harvest/response.rs
Labels: changelog:admin

#1105 Hide child list in "change order" UI if sorted alphabetically
  frontend/src/routes/manage/Realm/ChildOrder.tsx
Labels: changelog:user

#1110 Add realm acl roles to db dump
  .deployment/files/realms.yaml
  backend/src/cmd/import_realm_tree.rs
Labels: changelog:dev

#1111 Revise download menu listitems
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/manage/Video/TechnicalDetails.tsx
Labels: changelog:user

#1113 Update Paella and add support for fallback fullscreen mode on iOS
  frontend/package-lock.json
  frontend/package.json
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user

#1032 Make auth system more flexible & convenient and add "callbacks"
  .deployment/templates/config.toml
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/auth/cache.rs
  backend/src/auth/config.rs
  backend/src/auth/handlers.rs
  backend/src/auth/mod.rs
  backend/src/cmd/known_groups.rs
  backend/src/cmd/known_users.rs
  backend/src/config/general.rs
  backend/src/config/mod.rs
  backend/src/config/opencast.rs
  backend/src/http/assets.rs
  backend/src/http/handlers.rs
  backend/src/http/mod.rs
  backend/src/http/response.rs
  backend/src/metrics.rs
  backend/src/rss.rs
  backend/src/search/mod.rs
  backend/src/sync/stats.rs
  backend/src/util.rs
  docs/docs/setup/auth/in-depth.md
  docs/docs/setup/auth/index.md
  docs/docs/setup/auth/login-proxy.md
  docs/docs/setup/auth/user.md
  docs/docs/setup/auth/user/callback.md
  docs/docs/setup/auth/user/index.md
  docs/docs/setup/auth/user/tobira-session.md
  docs/docs/setup/auth/user/trust-auth-headers.md
  docs/docs/setup/config.toml
  frontend/src/config.ts
  frontend/src/index.tsx
  frontend/src/layout/header/UserBox.tsx
  util/dev-config/config.toml
Labels: changelog:breaking, changelog:admin

#1117 Fix login page redirect when `login_link` is not configured
  frontend/src/index.tsx
Labels: changelog:user

#1099 Add initial support for Matomo data collection via Paella player
  backend/src/config/matomo.rs
  backend/src/config/mod.rs
  backend/src/config/player.rs
  backend/src/http/assets.rs
  backend/src/http/handlers.rs
  docs/docs/setup/config.toml
  docs/docs/setup/matomo.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/config.ts
  frontend/src/index.html
  frontend/src/routes/Embed.tsx
  frontend/src/typings/paella-user-tracking.d.ts
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/player/Paella.tsx
  frontend/src/ui/player/index.tsx
Labels: changelog:admin

#1116 Make sure all users always have ROLE_USER and ROLE_ANONYMOUS
  backend/src/auth/handlers.rs
  backend/src/auth/mod.rs
Labels: changelog:breaking

#1115 Future proof harvest sync code for new items
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/sync/harvest/mod.rs
  backend/src/sync/harvest/response.rs
Labels: changelog:admin

#1122 Adjust paella quality selector css
  frontend/src/routes/Video.tsx
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user, area:player

#1124 Update authkit documentation & bump to version 0.2.0
  docs/docs/setup/auth/user/tobira-session.md
  util/authkit/CHANGELOG.md
  util/authkit/README.md
  util/authkit/package.json
Labels: changelog:admin
