Repository elan-ev/tobira, pull requests merged in 2024-10, with the labels that each got.

#1256 Fix deserialization of old harvest responses
  backend/src/db/types.rs
  backend/src/sync/harvest/minimal-response.json
  backend/src/sync/harvest/response.rs
  backend/src/sync/harvest/v1.0-response.json
Labels: changelog:admin

#1258 Improve main README with image and more up to date text
  .github/readme-image.avif
  README.md
Labels: changelog:nope

#1225 Change `mount_series` endpoint to accept and move existing series
  backend/src/api/mod.rs
  backend/src/api/model/realm/mod.rs
  backend/src/api/model/realm/mutations.rs
  backend/src/api/model/series.rs
  backend/src/api/mutation.rs
  backend/src/auth/mod.rs
  frontend/src/schema.graphql
Labels: changelog:dev

#1259 Do some dependency updates
  backend/Cargo.lock
  backend/Cargo.toml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/manage/Realm/util.tsx
  frontend/src/ui/Blocks/Text.tsx
Labels: changelog:admin

#1261 Update to `confique` 0.3
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/auth/config.rs
  backend/src/config/color.rs
  backend/src/config/mod.rs
  backend/src/config/opencast.rs
  backend/src/config/theme.rs
  backend/src/db/mod.rs
  backend/src/main.rs
Labels: changelog:dev

#1263 Add docs about connecting to a local Opencast
  docs/docs/dev/create-release.md
  docs/docs/dev/data.md
  docs/docs/dev/editor.md
  docs/docs/dev/local-opencast.md
  docs/docs/dev/tests.md
  docs/docs/dev/various-info.md
  util/containers/README.md
Labels: changelog:dev
