Repository elan-ev/tobira, pull requests merged in 2024-07, with the labels that each got.

#1193 Ignore `build` and `node_modules` folder for `webpack --watch`
  frontend/webpack.config.ts
Labels: changelog:dev

#1192 Fix uploader for metadata containing '%'
  frontend/src/routes/Upload.tsx
Labels: changelog:user

#1159 Add playlists to sync code, DB & API and add playlist direct links
  backend/src/api/id.rs
  backend/src/api/model/event.rs
  backend/src/api/model/mod.rs
  backend/src/api/model/playlist/mod.rs
  backend/src/api/model/series.rs
  backend/src/api/query.rs
  backend/src/db/cmd.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/35-playlists.sql
  backend/src/db/types.rs
  backend/src/sync/harvest/mod.rs
  backend/src/sync/harvest/response.rs
  backend/src/util.rs
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/router.tsx
  frontend/src/routes/NotFound.tsx
  frontend/src/routes/Playlist.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Series.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Blocks/VideoList.tsx
  frontend/src/ui/Video.tsx
  frontend/src/util/index.ts
Labels: changelog:user

#1199 Update appkit and replace own components by the ones from appkit
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/layout/header/Search.tsx
  frontend/src/layout/header/UserBox.tsx
  frontend/src/relay/auth.tsx
  frontend/src/relay/boundary.tsx
  frontend/src/routes/Embed.tsx
  frontend/src/routes/Login.tsx
  frontend/src/routes/Realm.tsx
  frontend/src/routes/Search.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/AddChild.tsx
  frontend/src/routes/manage/Realm/ChildOrder.tsx
  frontend/src/routes/manage/Realm/Content/Block.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Series.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/index.tsx
  frontend/src/routes/manage/Realm/Content/index.tsx
  frontend/src/routes/manage/Realm/DangerZone.tsx
  frontend/src/routes/manage/Realm/General.tsx
  frontend/src/routes/manage/Realm/RealmPermissions.tsx
  frontend/src/routes/manage/Realm/index.tsx
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/ui/Access.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/Button.tsx
  frontend/src/ui/Card.tsx
  frontend/src/ui/InitialConsent.tsx
  frontend/src/ui/Input.tsx
  frontend/src/ui/LinkButton.tsx
  frontend/src/ui/Modal.tsx
  frontend/src/ui/PathSegmentInput.tsx
  frontend/src/ui/SearchableSelect.tsx
  frontend/src/ui/Spinner.tsx
  frontend/src/ui/Waiting.tsx
  frontend/src/ui/error.tsx
  frontend/src/ui/player/index.tsx
Labels: changelog:dev

#1201 Fix comment in config for `general.initial_consent`
  backend/src/config/general.rs
  docs/docs/setup/config.toml
Labels: changelog:admin

#1207 Remove "open in new tab" icons from Editor and Studio buttons
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/routes/manage/index.tsx
Labels: changelog:user

#1206 Improve config docs for `general.initial_consent`
  backend/src/config/general.rs
  docs/docs/setup/config.toml
Labels: changelog:admin

#1205 Enable auto updates for test deploy server
  .deployment/requirements.yml
  .deployment/setup-server.yml
Labels: changelog:nope

#1204 Fix navigation for invalid realm paths
  frontend/src/routes/Realm.tsx
Labels: kind:bug, changelog:user

#1210 Fix back button by replacing current state in "forward to direct video"
  frontend/src/routes/Video.tsx
Labels: changelog:user

#1208 Fix various UI things in our paella integration
  frontend/package-lock.json
  frontend/package.json
  frontend/src/icons/settings.svg
  frontend/src/ui/player/Paella.tsx
  frontend/webpack.config.ts
Labels: changelog:user

#1211 Fix docs about "listed" behavior
  backend/src/api/model/event.rs
  docs/docs/semantics.md
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
Labels: changelog:admin

#1213 Refine notes for missing videos in series and playlist blocks
  backend/src/api/model/event.rs
  backend/src/api/model/playlist/mod.rs
  backend/src/api/model/series.rs
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/header/UserBox.tsx
  frontend/src/routes/util.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Blocks/Playlist.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Blocks/VideoList.tsx
  frontend/tests/util/user.ts
Labels: changelog:user
