Repository elan-ev/tobira, pull requests merged in 2024-09, with the labels that each got.

#1236 Fix random breakages
  .github/workflows/ci.yml
  frontend/tests/videoPage.spec.ts
Labels: changelog:nope

#1189 Add ability to find events by slide text & captions in search
  .github/workflows/upload-db-dump.yml
  .gitignore
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/api/common.rs
  backend/src/api/id.rs
  backend/src/api/model/search/event.rs
  backend/src/api/model/search/mod.rs
  backend/src/args.rs
  backend/src/auth/mod.rs
  backend/src/cmd/known_users.rs
  backend/src/config/opencast.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/38-event-texts.sql
  backend/src/db/types.rs
  backend/src/db/util.rs
  backend/src/main.rs
  backend/src/search/event.rs
  backend/src/search/mod.rs
  backend/src/sync/client.rs
  backend/src/sync/cmd.rs
  backend/src/sync/mod.rs
  backend/src/sync/text/mod.rs
  backend/src/sync/text/mpeg7.rs
  backend/src/util.rs
  docs/docs/setup/config.toml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Search.tsx
  frontend/src/schema.graphql
  frontend/tests/search.spec.ts
  util/scripts/db-load-dump.sh
Labels: changelog:user

#1179 Add `createRealmLineage` mutation to API
  backend/src/api/model/realm/mod.rs
  backend/src/api/model/realm/mutations.rs
  backend/src/api/mutation.rs
  frontend/src/schema.graphql
Labels: changelog:admin

#1241 Update Grafana to 11.2 on test deployment
  .deployment/monitoring/requirements.yml
  .deployment/monitoring/setup.yml
Labels: changelog:nope

#1245 Update paella-core to 1.49.6
  frontend/package-lock.json
  frontend/package.json
Labels: changelog:user
