Repository elan-ev/tobira, pull requests merged in 2024-01, with the labels that each got.

#1051 Improve homepage of test deployment
  .deployment/files/realms.yaml
Labels: changelog:nope

#1055 Fix `search` test that were randomly failing
  frontend/tests/search.spec.ts
Labels: changelog:nope

#1052 Fix migration logging output
  backend/src/db/migrations.rs
Labels: changelog:nope

#1064 Prevent search form submission
  frontend/src/layout/header/Search.tsx
Labels: area:frontend, kind:bug, status:ready, priority:low, changelog:nope

#1068 Speed up CI for `master`
  .github/workflows/ci.yml
Labels: area:ci, changelog:nope

#1062 Filter out past live events from search results in backend
  backend/src/api/model/search/mod.rs
  backend/src/search/event.rs
  backend/src/search/mod.rs
  frontend/src/routes/Search.tsx
Labels: changelog:user

#1061 Minor UI improvements
  frontend/src/layout/Root.tsx
  frontend/src/routes/Series.tsx
  frontend/src/routes/Video.tsx
  frontend/src/ui/Input.tsx
Labels: changelog:user

#1059 Add `changelog:nope` to `release.yml`
  .github/release.yml
Labels: changelog:nope

#1060 Fix router bug accessing `null` `history.state`
  frontend/src/index.tsx
  frontend/src/rauta.tsx
Labels: changelog:user

#1020 Improve series block ux
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Video.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/metadata.tsx
Labels: changelog:user

#1069 Speed up CI some more
  .github/workflows/ci.yml
  backend/Cargo.toml
Labels: area:ci, changelog:nope

#1021 Simplify edit series form
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Series.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
  frontend/src/ui/Input.tsx
Labels: changelog:user

#1071 Fix series block video items for screen widths 880 - 890
  frontend/src/GlobalStyle.tsx
  frontend/src/ui/Blocks/Series.tsx
Labels: changelog:user

#1001 Add arrow navigation to remaining popover menus
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/routes/manage/Realm/Content/AddButtons.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/FloatingBaseMenu.tsx
Labels: changelog:user

#1075 Rename `view` to `layout` and adjust spacing
  backend/src/api/model/block/mod.rs
  backend/src/api/model/block/mutations.rs
  backend/src/api/mutation.rs
  backend/src/cmd/import_realm_tree.rs
  backend/src/db/migrations/29-extend-series-block.sql
  backend/src/db/tests/util.rs
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/manage/Realm/Content/AddButtons.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Series.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Blocks/Series.tsx
Labels: changelog:nope

#1073 Split `ci` action into two jobs to start deploy faster
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
Labels: changelog:dev

#1085 Add breadcrumbs to series pages
  frontend/src/routes/Series.tsx
Labels: changelog:user

#1083 Make logout button work with keyboard
  frontend/src/layout/header/UserBox.tsx
Labels: changelog:user

#1088 Fix non-direct video links on search page
  frontend/src/routes/Video.tsx
Labels: changelog:nope
