Repository elan-ev/tobira, pull requests merged in 2024-05, with the labels that each got.

#1147 Reenable block editing UI tests
  frontend/tests/blocks.spec.ts
  frontend/tests/blocks.spec.ts_
  frontend/tests/dangerZone.spec.ts
  frontend/tests/empty.spec.ts
  frontend/tests/languageSelection.spec.ts
  frontend/tests/login.spec.ts
  frontend/tests/realms.spec.ts
  frontend/tests/search.spec.ts
  frontend/tests/util/blocks.ts
  frontend/tests/util/common.ts
  frontend/tests/util/realm.ts
  frontend/tests/videoPage.spec.ts
Labels: changelog:dev

#1167 Make font configurable, improve asset handling and use basic frontend bundle splitting
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/cmd/check.rs
  backend/src/config/mod.rs
  backend/src/config/theme.rs
  backend/src/config/translated_string.rs
  backend/src/http/assets.rs
  backend/src/http/handlers.rs
  docs/docs/setup/config.toml
  docs/docs/setup/theme.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/config.ts
  frontend/src/fonts.css
  frontend/src/index.html
  frontend/src/layout/header/Logo.tsx
  frontend/src/layout/header/Search.tsx
  frontend/src/ui/player/index.tsx
  frontend/webpack.config.ts
Labels: changelog:admin

#1164 Add migration for custom ACL actions
  backend/src/db/migrations.rs
  backend/src/db/migrations/32-custom-actions.sql
  backend/src/db/types.rs
  backend/src/sync/harvest/mod.rs
  backend/src/sync/harvest/response.rs
Labels: changelog:dev

#1165 Adjust sizing and color of new paella icons
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user

#1171 Remove obsolete `version` field from `docker-compose` files
  util/containers/docker-compose.yml
Labels: kind:improvement, area:build-system, changelog:nope
