Repository elan-ev/tobira, pull requests merged in 2025-05, with the labels that each got.

#1374 Make event title and description editable, add series column to "my videos"
  backend/src/api/model/event.rs
  backend/src/api/model/series.rs
  backend/src/api/model/shared.rs
  backend/src/api/mutation.rs
  backend/src/sync/client.rs
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/manage/Series/Create.tsx
  frontend/src/routes/manage/Series/SeriesDetails.tsx
  frontend/src/routes/manage/Shared/Details.tsx
  frontend/src/routes/manage/Video/VideoDetails.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/schema.graphql
  frontend/src/ui/metadata.tsx
Labels: changelog:user

#1414 Allow changing built-in group info (e.g. label of ROLE_USER)
  backend/src/api/model/acl.rs
  docs/docs/setup/config.md
  frontend/src/routes/manage/Realm/RealmPermissions.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Access.tsx
Labels: changelog:admin

#1422 Disable ToS prompt on embed routes
  frontend/src/ui/InitialConsent.tsx
Labels: changelog:user

#1426 Adjust dark-mode active/non-active/hover colors in ACL editor
  frontend/src/ui/Access.tsx
Labels: changelog:user

#1425 Add series link to locked video ACLs
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Upload.tsx
  frontend/src/routes/manage/Series/Shared.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/routes/manage/Video/VideoAccess.tsx
Labels: changelog:user, changelog:dev

#1428 Make harvest code able to deal with full batches of unreadable items
  backend/src/sync/harvest/mod.rs
Labels: changelog:admin

#1434 Do some dependency updates
  backend/Cargo.lock
  frontend/package-lock.json
  frontend/package.json
Labels: changelog:dev

#1437 Fix keyboard navigation in share modal tabs
  frontend/src/routes/Video.tsx
  frontend/src/ui/Blocks/VideoList.tsx
  frontend/src/ui/ShareButton.tsx
Labels: changelog:nope

#1432 Improve accessibility in some areas
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/header/Search.tsx
  frontend/src/routes/Realm.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/ui/Input.tsx
  frontend/src/ui/player/PlayerContext.tsx
  frontend/src/util/index.ts
  frontend/tests/blocks.spec.ts
Labels: changelog:user

#1438 Enable some paella config options
  frontend/src/i18n/.DS_Store
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user

#1443 Fix uploader css and wrongly locked ACL editing
  frontend/src/routes/Upload.tsx
  frontend/src/ui/Access.tsx
Labels: changelog:nope

#1444 Pre release fixes 3.3
  backend/src/api/model/series.rs
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Upload.tsx
  frontend/src/routes/manage/Shared/EditVideoList.tsx
  frontend/src/schema.graphql
Labels: changelog:nope

#1447 Fix Paella fullscreen on iOS
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user
