Repository elan-ev/tobira, pull requests merged in 2025-02, with the labels that each got.

#1322 Remove instant search from main search
  frontend/src/layout/header/Search.tsx
  frontend/src/layout/header/index.tsx
  frontend/src/routes/Search.tsx
  frontend/src/ui/LoadingIndicator.tsx
  frontend/tests/search.spec.ts
Labels: changelog:user

#1328 Add a new JWT key for local development
  util/dev-config/jwt-key.pem
Labels: changelog:dev

#1327 Limit number of text matches returned in search
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/api/model/search/event.rs
  backend/src/api/model/search/mod.rs
  backend/src/search/event.rs
  frontend/relay.config.js
  frontend/src/routes/Search.tsx
  frontend/src/schema.graphql
Labels: changelog:nope

#1337 Fix known groups/users label-related default key and typing
  backend/src/cmd/known_groups.rs
  backend/src/model/translated_string.rs
  frontend/relay.config.js
  frontend/src/routes/Upload.tsx
  frontend/src/ui/Access.tsx
Labels: changelog:nope

#1340 Minor doc fixes & improvements
  backend/src/logger.rs
  docs/docs/dev/create-release.md
  docs/docs/setup/ansible-example.md
  docs/docs/setup/config.toml
  docs/docs/setup/requirements.md
Labels: changelog:nope

#1311 Add "My series" page
  backend/src/api/common.rs
  backend/src/api/mod.rs
  backend/src/api/model/event.rs
  backend/src/api/model/mod.rs
  backend/src/api/model/search/mod.rs
  backend/src/api/model/search/series.rs
  backend/src/api/model/series.rs
  backend/src/api/model/shared.rs
  backend/src/api/model/user.rs
  backend/src/api/util.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/41-series-index.sql
  backend/src/db/types.rs
  backend/src/model/event/mod.rs
  backend/src/model/mod.rs
  backend/src/model/series/mod.rs
  backend/src/search/series.rs
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/header/UserBox.tsx
  frontend/src/router.tsx
  frontend/src/routes/Search.tsx
  frontend/src/routes/manage/Series/index.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/routes/manage/shared.tsx
  frontend/src/schema.graphql
  frontend/src/ui/metadata.tsx
Labels: changelog:user
