Repository elan-ev/tobira, pull requests merged in 2025-03, with the labels that each got.

#1350 Fix pagination overflow
  frontend/src/routes/manage/shared.tsx
Labels: changelog:nope

#1353 Fix series acl lock
  frontend/src/routes/Upload.tsx
Labels: changelog:user

#1347 Optimize GQL queries
  backend/src/api/model/realm/mod.rs
  frontend/src/routes/Realm.tsx
  frontend/src/ui/Blocks/index.tsx
Labels: changelog:admin

#1345 Show deleted blocks only in edit mode
  frontend/src/routes/manage/Realm/Content/Block.tsx
  frontend/src/ui/Blocks/Playlist.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/Blocks/index.tsx
Labels: changelog:user

#1357 Fix `tobira worker` on single-CPU machines by using fewer DB connections
  backend/src/auth/mod.rs
  backend/src/main.rs
  backend/src/search/cmd.rs
  backend/src/search/update.rs
  backend/src/sync/cmd.rs
  backend/src/sync/harvest/mod.rs
  backend/src/sync/mod.rs
  backend/src/sync/stats.rs
  backend/src/sync/text/mod.rs
Labels: kind:bug, changelog:admin

#1358 Make JWT contain auth claims to grant correct permissions
  backend/src/api/jwt.rs
  backend/src/api/query.rs
  backend/src/auth/jwt.rs
  frontend/src/relay/auth.tsx
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/schema.graphql
Labels: changelog:admin

#1348 Add configurable deletion modes for series, events and playlists
  backend/src/api/model/block/mod.rs
  backend/src/config/theme.rs
  backend/src/sync/harvest/mod.rs
  backend/src/sync/harvest/response.rs
  backend/src/sync/mod.rs
  docs/docs/setup/config.toml
Labels: changelog:user

#1373 Add created date to series selection dropdown
  backend/src/api/model/search/series.rs
  frontend/src/schema.graphql
  frontend/src/ui/SearchableSelect.tsx
Labels: changelog:user
