Repository elan-ev/tobira, pull requests merged in 2025-06, with the labels that each got.

#1451 Fix Paella popup menus not working in iOS fake fullscreen
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user

#1457 Make "go back" navigation work after error boundary has been triggered
  frontend/src/util/err.tsx
Labels: changelog:user

#1458 Clean up translations
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/Footer.tsx
  frontend/src/layout/header/UserBox.tsx
  frontend/src/routes/Login.tsx
  frontend/src/routes/Playlist.tsx
  frontend/src/routes/Realm.tsx
  frontend/src/routes/Series.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/Content/Block.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Playlist.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Series.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Text.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Title.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/index.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/util.tsx
  frontend/src/routes/manage/Realm/Content/Edit/RemoveButton.tsx
  frontend/src/routes/manage/Realm/Content/Edit/index.tsx
  frontend/src/routes/manage/Realm/DangerZone.tsx
  frontend/src/routes/manage/Realm/General.tsx
  frontend/src/routes/manage/Realm/RealmPermissions.tsx
  frontend/src/routes/manage/Series/Create.tsx
  frontend/src/routes/manage/Series/SeriesAccess.tsx
  frontend/src/routes/manage/Series/SeriesDetails.tsx
  frontend/src/routes/manage/Series/Shared.tsx
  frontend/src/routes/manage/Series/index.tsx
  frontend/src/routes/manage/Shared/Access.tsx
  frontend/src/routes/manage/Shared/Details.tsx
  frontend/src/routes/manage/Shared/EditVideoList.tsx
  frontend/src/routes/manage/Shared/Table.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/routes/manage/Video/TechnicalDetails.tsx
  frontend/src/routes/manage/Video/VideoAccess.tsx
  frontend/src/routes/manage/Video/VideoDetails.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/ui/Access.tsx
  frontend/src/ui/Blocks/Playlist.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/Blocks/VideoList.tsx
  frontend/src/ui/EventSelector.tsx
  frontend/src/ui/Input.tsx
  frontend/src/ui/Modal.tsx
  frontend/src/ui/metadata.tsx
  util/scripts/i18n/compare-keys.js
  util/scripts/i18n/find-duplicate-keys.js
  util/scripts/i18n/find-unused-keys.js
Labels: changelog:dev

#1465 Update paella-user-tracking to 1.42.6
  frontend/package-lock.json
  frontend/package.json
Labels: changelog:admin

#1466 Add "unlisted" to filterable playlist fields
  backend/src/search/playlist.rs
  frontend/tests/blocks.spec.ts
  frontend/tests/fixtures/standard.sql
  frontend/tests/util/blocks.ts
Labels: changelog:user
