Repository elan-ev/tobira, pull requests merged in 2025-01, with the labels that each got.

#1292 Allow configuring logos for multiple languages
  .deployment/templates/config.toml
  backend/src/cmd/check.rs
  backend/src/config/mod.rs
  backend/src/config/theme.rs
  backend/src/config/translated_string.rs
  backend/src/http/assets.rs
  backend/src/sync/stats.rs
  docs/docs/setup/config.toml
  docs/docs/setup/theme.md
  frontend/src/config.ts
  frontend/src/layout/header/Logo.tsx
  frontend/src/ui/InitialConsent.tsx
  frontend/src/util/index.ts
  frontend/tests/util/isolation.ts
  util/dev-config/config.toml
Labels: changelog:breaking, changelog:admin

#1310 Remove frame control button plugin
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user

#1316 Make known group labels require 'default' instead of 'en'
  .deployment/files/known-groups.json
  backend/src/api/model/acl.rs
  backend/src/api/model/known_roles.rs
  backend/src/api/util.rs
  backend/src/cmd/known_groups.rs
  backend/src/config/general.rs
  backend/src/config/translated_string.rs
  docs/docs/setup/config.toml
  frontend/src/schema.graphql
  frontend/src/ui/Access.tsx
Labels: changelog:nope

#1305 Add config to lock video ACLs to their series
  backend/src/api/model/event.rs
  backend/src/api/model/series.rs
  backend/src/config/general.rs
  backend/src/http/assets.rs
  docs/docs/setup/config.toml
  frontend/src/config.ts
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Upload.tsx
  frontend/src/routes/manage/Realm/RealmPermissions.tsx
  frontend/src/routes/manage/Video/Access.tsx
  frontend/src/routes/util.tsx
  frontend/src/schema.graphql
  frontend/src/ui/SearchableSelect.tsx
Labels: changelog:user

#1319 Improve search backend: add stop words, use "federated search", highlight creators
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/api/model/search/event.rs
  backend/src/api/model/search/mod.rs
  backend/src/api/model/search/realm.rs
  backend/src/api/model/search/series.rs
  backend/src/search/event.rs
  backend/src/search/mod.rs
  backend/src/search/stop-words.txt
  backend/src/search/util.rs
  backend/vendor/README.md
  backend/vendor/meilisearch-sdk/.gitignore
  backend/vendor/meilisearch-sdk/CONTRIBUTING.md
  backend/vendor/meilisearch-sdk/Cargo.toml
  backend/vendor/meilisearch-sdk/LICENSE
  backend/vendor/meilisearch-sdk/README.md
  backend/vendor/meilisearch-sdk/README.tpl
  backend/vendor/meilisearch-sdk/bors.toml
  backend/vendor/meilisearch-sdk/docker-compose.yml
  backend/vendor/meilisearch-sdk/meilisearch-index-setting-macro/Cargo.toml
  backend/vendor/meilisearch-sdk/meilisearch-index-setting-macro/src/lib.rs
  backend/vendor/meilisearch-sdk/meilisearch-test-macro/Cargo.toml
  backend/vendor/meilisearch-sdk/meilisearch-test-macro/README.md
  backend/vendor/meilisearch-sdk/meilisearch-test-macro/src/lib.rs
  backend/vendor/meilisearch-sdk/scripts/check-readme.sh
  backend/vendor/meilisearch-sdk/scripts/update-readme.sh
  backend/vendor/meilisearch-sdk/scripts/update_macro_versions.sh
  backend/vendor/meilisearch-sdk/src/.client.rs.pending-snap
  backend/vendor/meilisearch-sdk/src/client.rs
  backend/vendor/meilisearch-sdk/src/documents.rs
  backend/vendor/meilisearch-sdk/src/dumps.rs
  backend/vendor/meilisearch-sdk/src/errors.rs
  backend/vendor/meilisearch-sdk/src/features.rs
  backend/vendor/meilisearch-sdk/src/indexes.rs
  backend/vendor/meilisearch-sdk/src/key.rs
  backend/vendor/meilisearch-sdk/src/lib.rs
  backend/vendor/meilisearch-sdk/src/request.rs
  backend/vendor/meilisearch-sdk/src/reqwest.rs
  backend/vendor/meilisearch-sdk/src/search.rs
  backend/vendor/meilisearch-sdk/src/settings.rs
  backend/vendor/meilisearch-sdk/src/snapshots.rs
  backend/vendor/meilisearch-sdk/src/task_info.rs
  backend/vendor/meilisearch-sdk/src/tasks.rs
  backend/vendor/meilisearch-sdk/src/tenant_tokens.rs
  backend/vendor/meilisearch-sdk/src/utils.rs
  docs/docs/setup/requirements.md
  frontend/src/routes/Search.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Video.tsx
  util/containers/docker-compose.yml
  util/scripts/check-system.sh
Labels: changelog:breaking

#1321 Improve frontend performance by avoiding useless renders
  frontend/src/App.tsx
  frontend/src/layout/Root.tsx
  frontend/src/layout/header/Search.tsx
  frontend/src/rauta.tsx
  frontend/src/router.tsx
  frontend/src/ui/LoadingIndicator.tsx
Labels: changelog:user

#1324 Various search improvements
  backend/src/api/model/search/mod.rs
  frontend/src/routes/Search.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Video.tsx
Labels: changelog:user
