Repository elan-ev/tobira, pull requests merged in 2025-07, with the labels that each got.

#1478 Add icon designer helper and script to check migrations between versions
  util/icon-designer/README.md
  util/icon-designer/icon.svg
  util/icon-designer/index.html
  util/scripts/migration-check.sh
Labels: changelog:dev

#1483 Use internal `Link` links for internal links in text blocks
  frontend/src/ui/Blocks/Text.tsx
Labels: changelog:user

#1482 Fix Tobira needlessly reloading when going back
  frontend/src/ui/player/Paella.tsx
  frontend/src/util/err.tsx
Labels: changelog:user, changelog:dev

#1484 Make breadcrumbs show realm path for video/series "not found" page
  frontend/src/routes/NotFound.tsx
  frontend/src/routes/Series.tsx
  frontend/src/routes/Video.tsx
Labels: changelog:user

#1477 Redesign realm navigation (and add `DevConfig` helper)
  backend/src/api/model/realm/mod.rs
  backend/src/api/model/realm/nav.rs
  frontend/src/App.tsx
  frontend/src/DevConfig.tsx
  frontend/src/layout/Burger.tsx
  frontend/src/layout/Navigation.tsx
  frontend/src/routes/About.tsx
  frontend/src/routes/Playlist.tsx
  frontend/src/routes/Realm.tsx
  frontend/src/routes/Series.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/AddChild.tsx
  frontend/src/routes/manage/Realm/ChildOrder.tsx
  frontend/src/routes/manage/Realm/Content/index.tsx
  frontend/src/routes/manage/Realm/index.tsx
  frontend/src/schema.graphql
  frontend/tests/realms.spec.ts
Labels: changelog:user

#1491 Enable GraphQL Playground
  backend/src/http/handlers.rs
Labels: changelog:admin

#1494 Various bug fixes and minor improvements
  frontend/src/routes/Video.tsx
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/Blocks/VideoList.tsx
  frontend/src/ui/PathSegmentInput.tsx
  frontend/src/ui/ShareButton.tsx
  frontend/src/ui/player/PlayerContext.tsx
  frontend/src/ui/player/index.tsx
Labels: changelog:user

#1389 Add placeholder for unsynced events
  backend/src/api/model/event.rs
  backend/src/api/mutation.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/43-search-views-without-deletions.sql
  backend/src/db/migrations/44-redo-events-no-null-tracks-constraint.sql
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/routes/Search.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/manage/Realm/RealmPermissions.tsx
  frontend/src/routes/manage/Series/Create.tsx
  frontend/src/routes/manage/Series/SeriesAccess.tsx
  frontend/src/routes/manage/Series/SeriesDetails.tsx
  frontend/src/routes/manage/Series/Shared.tsx
  frontend/src/routes/manage/Series/index.tsx
  frontend/src/routes/manage/Shared/Access.tsx
  frontend/src/routes/manage/Shared/Details.tsx
  frontend/src/routes/manage/Shared/Table.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/routes/manage/Video/VideoAccess.tsx
  frontend/src/routes/manage/Video/VideoDetails.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/routes/util.tsx
  frontend/src/schema.graphql
  frontend/src/ui/ThumbnailStack.tsx
  frontend/src/ui/Video.tsx
Labels: changelog:user

#1498 Fix inert series link on locked acl pages
  frontend/src/routes/manage/Shared/Access.tsx
  frontend/src/routes/manage/Video/VideoAccess.tsx
Labels: changelog:user

#1500 Add caching for Paella SVG icons
  backend/src/http/assets.rs
  frontend/src/config.ts
  frontend/src/ui/player/Paella.tsx
Labels: changelog:user

#1502 Fix "global page admins" appearing in ACL UI for events/series
  frontend/src/i18n/locales/de.yaml
  frontend/src/ui/Access.tsx
Labels: changelog:user

#1499 Add `auth.hide_login_button` config
  backend/src/auth/config.rs
  backend/src/http/assets.rs
  docs/docs/setup/config.toml
  frontend/src/config.ts
  frontend/src/layout/header/UserBox.tsx
Labels: changelog:admin
