Repository elan-ev/tobira, pull requests merged in 2025-04, with the labels that each got.

#1375 Update appkit to 0.4, react-icons to 5.5, and focus-trap-react to 11
  frontend/package-lock.json
  frontend/package.json
  frontend/src/layout/header/UserBox.tsx
  frontend/src/routes/Embed.tsx
  frontend/src/routes/Realm.tsx
  frontend/src/routes/Search.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/index.tsx
  frontend/src/routes/manage/Realm/Content/Edit/index.tsx
  frontend/src/routes/manage/Realm/index.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/routes/util.tsx
  frontend/src/ui/Blocks/Video.tsx
  frontend/src/ui/Blocks/VideoList.tsx
  frontend/src/ui/Breadcrumbs.tsx
  frontend/src/ui/Video.tsx
  frontend/src/ui/index.tsx
  frontend/src/util/index.ts
  frontend/webpack.config.ts
Labels: changelog:user, changelog:dev

#1313 Add series management pages
  backend/src/api/model/event.rs
  backend/src/api/model/series.rs
  backend/src/api/model/shared.rs
  backend/src/api/mutation.rs
  backend/src/config/general.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/42-series-view-and-deletion-timestamp.sql
  backend/src/model/event/mod.rs
  backend/src/model/extra_metadata.rs
  backend/src/model/series/mod.rs
  backend/src/sync/client.rs
  backend/src/sync/harvest/mod.rs
  backend/src/sync/mod.rs
  docs/docs/setup/config.toml
  frontend/src/App.tsx
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/router.tsx
  frontend/src/routes/Search.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Series/SeriesAccess.tsx
  frontend/src/routes/manage/Series/SeriesDetails.tsx
  frontend/src/routes/manage/Series/Shared.tsx
  frontend/src/routes/manage/Series/index.tsx
  frontend/src/routes/manage/Shared/Access.tsx
  frontend/src/routes/manage/Shared/Details.tsx
  frontend/src/routes/manage/Shared/Nav.tsx
  frontend/src/routes/manage/Shared/Table.tsx
  frontend/src/routes/manage/Video/Access.tsx
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/routes/manage/Video/TechnicalDetails.tsx
  frontend/src/routes/manage/Video/VideoAccess.tsx
  frontend/src/routes/manage/Video/VideoDetails.tsx
  frontend/src/routes/manage/Video/index.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Access.tsx
  frontend/src/ui/NotificationContext.tsx
  frontend/src/ui/ThumbnailStack.tsx
  frontend/src/ui/Video.tsx
  frontend/src/ui/index.tsx
  frontend/src/ui/metadata.tsx
  frontend/src/ui/time.tsx
  frontend/src/util/index.tsx
  frontend/src/util/roles.tsx
Labels: changelog:user

#1394 Correct conflicting "no/missing videos" note
  frontend/src/i18n/locales/en.yaml
  frontend/src/ui/Blocks/VideoList.tsx
Labels: changelog:user

#1344 Update ESLint and `@opencast/eslint-config-ts-react`
  frontend/.eslintrc.js
  frontend/eslint.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/relay/boundary.tsx
  frontend/src/routes/NotFound.tsx
  frontend/src/routes/Realm.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Playlist.tsx
  frontend/src/routes/manage/Realm/Content/Edit/index.tsx
  frontend/src/routes/manage/Video/Access.tsx
  frontend/src/routes/manage/Video/Details.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/routes/util.tsx
  frontend/src/ui/Access.tsx
  frontend/src/ui/Input.tsx
  frontend/src/ui/Video.tsx
  frontend/src/ui/metadata.tsx
  frontend/src/ui/player/index.tsx
  frontend/src/util/err.tsx
  frontend/src/util/index.ts
  frontend/tests/login.spec.ts
  frontend/tests/realms.spec.ts
  frontend/tests/videoPage.spec.ts
  frontend/webpack.config.ts
  util/scripts/watch-frontend.sh
Labels: changelog:dev

#1406 Fix frontend watching & reloading
  util/scripts/watch-frontend.sh
Labels: changelog:dev

#1404 Sort series in series selector by `created` instead of `updated`
  backend/src/api/model/search/mod.rs
  backend/src/search/mod.rs
  backend/src/search/series.rs
Labels: changelog:user

#1410 Fix minor search rebuild problems
  backend/src/search/mod.rs
  backend/src/search/util.rs
Labels: changelog:admin

#1411 Add `itunes:author` tag to RSS feeds and make `itunes:explicit` value configurable
  backend/src/config/general.rs
  backend/src/rss.rs
  docs/docs/setup/config.toml
Labels: changelog:admin

#1325 Add "Create series" API and route
  backend/src/api/context.rs
  backend/src/api/model/event.rs
  backend/src/api/model/series.rs
  backend/src/api/model/user.rs
  backend/src/api/mutation.rs
  backend/src/auth/config.rs
  backend/src/auth/mod.rs
  backend/src/db/types.rs
  backend/src/model/mod.rs
  backend/src/model/series/mod.rs
  backend/src/sync/client.rs
  backend/src/sync/harvest/mod.rs
  docs/docs/setup/config.toml
  frontend/src/User.tsx
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/header/UserBox.tsx
  frontend/src/relay/boundary.tsx
  frontend/src/router.tsx
  frontend/src/routes/Series.tsx
  frontend/src/routes/Upload.tsx
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Series.tsx
  frontend/src/routes/manage/Realm/RealmPermissions.tsx
  frontend/src/routes/manage/Series/Create.tsx
  frontend/src/routes/manage/Series/SeriesAccess.tsx
  frontend/src/routes/manage/Series/SeriesDetails.tsx
  frontend/src/routes/manage/Series/Shared.tsx
  frontend/src/routes/manage/Series/index.tsx
  frontend/src/routes/manage/Shared/Access.tsx
  frontend/src/routes/manage/Shared/Details.tsx
  frontend/src/routes/manage/Shared/Table.tsx
  frontend/src/routes/manage/Video/VideoAccess.tsx
  frontend/src/routes/manage/Video/VideoDetails.tsx
  frontend/src/routes/manage/index.tsx
  frontend/src/routes/util.tsx
  frontend/src/schema.graphql
  frontend/src/ui/Access.tsx
  frontend/src/ui/Blocks/Series.tsx
  frontend/src/ui/Waiting.tsx
  frontend/src/ui/metadata.tsx
  frontend/src/util/index.tsx
  util/dummy-login/dist/index.js
  util/dummy-login/index.ts
Labels: changelog:user
