Repository elan-ev/tobira, pull requests merged in 2025-09, with the labels that each got.

#1540 Add config for tenant admin role
  backend/src/api/context.rs
  backend/src/api/jwt.rs
  backend/src/api/model/known_roles.rs
  backend/src/api/model/realm/mod.rs
  backend/src/api/model/realm/mutations.rs
  backend/src/api/model/search/event.rs
  backend/src/api/model/search/mod.rs
  backend/src/api/model/search/series.rs
  backend/src/api/model/series.rs
  backend/src/api/model/shared.rs
  backend/src/api/query.rs
  backend/src/auth/config.rs
  backend/src/auth/mod.rs
  backend/src/http/handlers.rs
  backend/src/model/event/mod.rs
  docs/docs/setup/config.toml
Labels: changelog:admin

#1546 Add EdDSA JWT support (with ed25519 curve) and switch from `ring` to `aws-lc-rs`
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/auth/jwt.rs
  docs/docs/setup/config.toml
  util/dev-config/ed25519-key.pem
Labels: area:auth, changelog:admin

#1550 Fix breadcrumbs for series & event results in search
  frontend/src/routes/Search.tsx
Labels: changelog:user

#1568 Correct `de` translation for "password"
  frontend/src/i18n/locales/de.yaml
Labels: changelog:nope

#1574 Fix favicon path in Markdown guide
  backend/src/http/assets.rs
  frontend/src/config.ts
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Text.tsx
Labels: changelog:user

#1580 Add share button to video details page
  frontend/src/routes/Video.tsx
  frontend/src/routes/manage/Shared/Details.tsx
  frontend/src/routes/manage/Video/Shared.tsx
  frontend/src/routes/manage/Video/VideoDetails.tsx
Labels: changelog:user
