Repository elan-ev/tobira, pull requests merged in 2025-08, with the labels that each got.

#1505 Add italian and french translations
  .deployment/files/known-groups.json
  .deployment/templates/config.toml
  backend/src/model/translated_string.rs
  frontend/src/i18n/index.ts
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/fr.yaml
  frontend/src/i18n/locales/it.yaml
  frontend/src/ui/Access.tsx
Labels: changelog:user

#1518 Improve error message for config `TranslatedLabel` being set to string
  backend/src/model/translated_string.rs
Labels: changelog:admin

#1516 Fix Rust warnings for Rust 1.89
  backend/src/auth/session_id.rs
  backend/vendor/meilisearch-sdk/src/client.rs
  backend/vendor/meilisearch-sdk/src/documents.rs
  backend/vendor/meilisearch-sdk/src/indexes.rs
Labels: changelog:nope

#1523 Fix log file path in error message
  backend/src/logger.rs
Labels: changelog:admin

#1524 Add `can_create_series` role to docs and explain "My *" visibility
  docs/docs/semantics.md
Labels: changelog:admin

#1531 Improve uploader by actually checking `/info/me.json` result
  frontend/src/routes/Upload.tsx
Labels: changelog:admin

#1520 Add formatting guide & live preview to text block editor
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/i18n/locales/fr.yaml
  frontend/src/i18n/locales/it.yaml
  frontend/src/routes/manage/Realm/Content/Edit/EditMode/Text.tsx
  frontend/src/ui/Blocks/Text.tsx
Labels: changelog:user

#1512 Add RSS link to series details
  frontend/src/i18n/locales/it.yaml
  frontend/src/routes/manage/Series/SeriesDetails.tsx
  frontend/src/routes/manage/Shared/Details.tsx
  frontend/src/ui/Blocks/VideoList.tsx
Labels: changelog:user

#1503 Add keyboard shortcuts for general functions and video player
  .github/workflows/ci.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/GlobalStyle.tsx
  frontend/src/i18n/index.ts
  frontend/src/i18n/locales/de.yaml
  frontend/src/i18n/locales/en.yaml
  frontend/src/layout/header/Search.tsx
  frontend/src/layout/header/UserBox.tsx
  frontend/src/routes/Video.tsx
  frontend/src/typings/paella-core.d.ts
  frontend/src/ui/Blocks/index.tsx
  frontend/src/ui/Shortcuts.tsx
  frontend/src/ui/player/Paella.tsx
  frontend/src/ui/player/PlayerGroupContext.tsx
  frontend/src/ui/player/PlayerShortcuts.tsx
  frontend/src/ui/player/consts.tsx
Labels: changelog:user, area:accessibility

#1536 Sort groups alphabetically in selector & add `sortKey` for more control
  backend/src/api/model/known_roles.rs
  backend/src/cmd/known_groups.rs
  backend/src/db/migrations.rs
  backend/src/db/migrations/46-known-groups-sort-key.sql
  docs/docs/setup/config.md
  frontend/src/schema.graphql
  frontend/src/ui/Access.tsx
Labels: changelog:user

#1538 Fix variables inside French translation
  frontend/src/i18n/locales/fr.yaml
Labels: changelog:nope
